### ISSUE TITLE
Missing Global values in grid.pyi

### ISSUE THREAD

**Issue by chacabuco** [AlexionSoftware/types-wxpython#15]
Hello,
Thanks for solving the lasts requests. Here is another one. I still don't understand whether these should be declared in the generator. An explanation would be much appreciated.

following global variables are missing in grid.pyi:
GRID_VALUE_STRING: str
GRID_VALUE_BOOL: str
GRID_VALUE_NUMBER: str
GRID_VALUE_FLOAT: str
GRID_VALUE_CHOICE: str
GRID_VALUE_DATE: str
GRID_VALUE_TEXT: str
GRID_VALUE_LONG: str
GRID_VALUE_CHOICEINT: str
GRID_VALUE_DATETIME: str

 which are present in wxpython:
https://github.com/wxWidgets/Phoenix/blob/master/etg/grid.py#L90

**Comment by martijnwiekens** [comment]
I updated the README to include information on how things work. 

What do you think?

**Comment by martijnwiekens** [comment]
I also created PR #17 for you to see.

**Comment by chacabuco** [comment]
In the overrises section on the readme there is a typo:
"we sometimes HAVE to resort to guessing,"

**Comment by chacabuco** [comment]
Now that I see the Pull Request, and how you added the variables. It is somewhat clearer. Thanks a lot!!!
