### ISSUE TITLE
`PlatformInfo` and `PlatformInformation`

### ISSUE THREAD

**Issue by quarthex** [AlexionSoftware/types-wxpython#26]
Hello,

There are two incorrect things, due to a misleading documentation.

- `PlatformInfo` is not a type alias for `tuple[blabla]`, but is a tuple itself.
- `PlatformInformation.Get()` does not return the `PlatformInfo` tuple, but rather an instance of `PlatformInformation`.

The documentation of wxPython is a mess. 😮‍💨
Thanks for the effort.

**Comment by JenteAlexion** [comment]
Thank you for notifying!
I've made changes for those.

**Comment by JenteAlexion** [comment]
Thank you for notifying.
I've added these changes and they will be available in the next build :)
