### ISSUE TITLE
Property names conflict with class names

### ISSUE THREAD

**Issue by udifuchs** [AlexionSoftware/types-wxpython#4]
PR #3 broke some types. The problem shows up when a property has the same name as a class.
For example, `Rect` in the `wx` namespace is a class name. But the `wx.Window` class also has a `Rect` property. 
```
import wx
w = wx.Window()
reveal_type(w)  # Revealed type is "wx.Window"
reveal_type(w.Rect)  # Revealed type is "wx.Rect"
reveal_type(w.Rect.Left)  # Revealed type is "builtins.int"
r = w.GetClientRect()
reveal_type(r)  # Revealed type is "Rect?"
reveal_type(r.Left)  # mypy error: Rect? has no attribute "Left"  [attr-defined]
```

I'm not sure if this is the intended behaviour of mypy or if it is a bug.
In any case, moving the class attribute to an instance attribute would solve the problem.
Something like:
```
class Window:
    def __init__(self) -> None:                                   
        self.Rect: 'Rect'  # See GetRect and SetRect
```

**Comment by martijnwiekens** [comment]
Let's see what we can do.
