### ISSUE TITLE
Declare properties as such

### ISSUE THREAD

**Issue by quarthex** [AlexionSoftware/types-wxpython#6]
Declaring properties as attributes leads to misleading messages.
For instance, `wx.Rect().Size.Width` will trigger the following warning:

    error: "Union?[Tuple[builtins.int, builtins.int], wx.Size]" has no attribute "Witdh"  [attr-defined]

It seems that mypy is able to interpret property declarations.

**Comment by martijnwiekens** [comment]
The `Union` typing should only be used for the SetSize method.
Somewhere it is using the `Set` typing.
Let's take a look.
